In [1]:
import numpy as np  #导入numpy库，用于矩阵操作和随机数生成
def create_matrix(N, M): #创建一个N行M列的矩阵
    matrix = np.random.randint(0, 2, size=(N, M))  #先随机填充 0 或 1，再进行改单元格操作
    matrix[0, 0] = 1  #进行矩阵操作左上角赋值为 1
    matrix[N-1, M-1] = 1  #进行矩阵操作右下角赋值为 1 
    return matrix #返回矩阵  

In [2]:
def Count_path(matrix): #创建路径函数
    N, M = matrix.shape #使用shape函数获取矩阵的行和列
    dp = np.zeros((N, M), dtype=int) # 创建动态规划数组，初始化为 0，此处参考了CSDN系统性动态规划分类总结（一）：dp数组定义与递推公式
    if matrix[0, 0] == 1: #判断起点是否，有可能存在[0,0]附近全是阻塞0
        dp[0, 0] = 1
        #由于要求给定的单元格只能向右或向下移动，所以需要单独对第一行和第一列做一次for遍历
    for j in range(1, M): #填充第一行（只能向右）
        if matrix[0, j] == 1 and dp[0, j-1] > 0: #确保当前格可通行，确保前一格有路径
            dp[0, j] = dp[0, j-1]
    for i in range(1, N): #填充第一列（只能向下）
        if matrix[i, 0] == 1 and dp[i-1, 0] > 0: #确保当前格可通行，确保前一格有路径
            dp[i, 0] = dp[i-1, 0]
    for i in range(1, N): # 填充其余单元格
        for j in range(1, M):
            if matrix[i, j] == 1:
                dp[i, j] = dp[i-1, j] + dp[i, j-1]  # 路径数为上方和左方可通行的路径之和
    return dp[N-1, M-1]

In [3]:
N, M = 10, 8  #设置矩阵大小
total_paths = 0  #存储1000次运行的路径总数
for _ in range(1000):
    matrix = create_matrix(N, M)
    paths = Count_path(matrix)
    total_paths += paths
average_paths = total_paths / 1000 #计算平均值
print(matrix)
print(f"1000次运行中路径总数的平均值：{average_paths}")

[[1 1 1 1 0 1 1 0]
 [1 1 1 0 1 1 0 0]
 [0 1 1 1 1 0 0 0]
 [1 0 0 0 1 1 1 0]
 [1 1 0 1 0 1 1 0]
 [0 1 0 1 0 0 0 1]
 [0 0 1 0 1 1 0 1]
 [0 0 1 0 1 1 1 1]
 [0 1 1 0 0 0 1 0]
 [0 1 0 1 1 0 0 1]]
1000次运行中路径总数的平均值：0.417
